name: CD

on:
  push:
    branches:
      - master

env:
  NODE_ENV: production
  NODE_VERSION: 15.x

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    env:
      CI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Set Up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        uses: actions/cache@v2.1.3
        with:
          path: $HOME/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Run Build
        run: |
          npm install
          npm run build
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          INTERCOM_APP_ID: ${{ secrets.INTERCOM_APP_ID }}
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@3.7.1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: public
      #     CLEAN: true
